### ISSUE TITLE
Don´t tell users to wipe out their config file.

### ISSUE THREAD

**Issue by DaveDavenport** [catppuccin/rofi#4]
The current install instructions will wipe out the users existing config.
This is very bad!

The theme should be fully in catppuccin.rasi, now it will break usage with `rofi-theme-selector`.

It is spit out partially in a `catppuccin.rasi`, parts are in config.rasi (why not append everything in `catppuccin.rasi` ?) and parts use deprecated options.

It should be moved into one file and updated to set config options in the right place:

show_icons: true;  should be part of theme:

```css
element {
    children: [element-icon, element-text];
}
```
Font should be set in theme:
```css
* {
   font: "JetBrainsMono Nerd Font 14";
}
```

lines should be set on listview:
```css
listview {
lines: 5;
}
```
etc.
